### PR TITLE
Main

### PR DESCRIPTION
**Pull request by AITHIOMB**
Translated this document, however it has not been cleaned yet.

### CODE REVIEW

**Comment by vamsi-bulusu** [comment]
Hi @AITHIOMB, I see that you are updating files in the raw dataset folder, can you create a folder for Sales Packaging inside the clean dataset folder and update the translated files in that directory?

**Comment by AITHIOMB** [comment]
Yes I can! Thanks for sharing the procedure. I'll do that from now on

**Comment by vamsi-bulusu** [comment]
@AITHIOMB Please UPDATE this PR with suggested changes

**Comment by AITHIOMB** [comment]
@vamsi-bulusu Will do!

**Comment by vamsi-bulusu** [comment]
Hi @AITHIOMB, Sales Packaging has been translated by @polixonrio

We are left with Hazardous Waste and Waste Disposal datasets.

Closing this PR for now.

**Comment by AITHIOMB** [comment]
Shout out to @polixonrio for doing such a great job!! @vamsi-bulusu  Thank you for letting me know which ones are still open, I'll go take a look.

**Pull request closed without merging**
